name: Create Pull Request for Release Branch

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: |
          echo $GITHUB_REF_NAME
          pr_list=$(gh pr list --head $GITHUB_REF_NAME --json number --jq '.[] | .number')
          if [ -n "$pr_list" ]; then
            echo "Pull request for branch $GITHUB_REF_NAME already exists"
          else
            gh pr create --fill --draft --base live
          fi
        env:
          GH_TOKEN: ${{ github.token }}
